### ISSUE TITLE
edicion de datos personales del estudiante

### ISSUE THREAD

**Issue by geovis159** [RedFox-SRL/backend#26]
----------
### Severidad

Alta

### Prioridad

alta

### Descripción

los campos de nombre , apellido , correo no cuentan con restricciones

### Pre-condiciones
se realiza el inicio d secion del estudiante 

Navegador Versión 128.0.6613.138

### Tipo de dispositivo
 laptop DELL

### ¿En qué navegadores encuentras el problema?

Google Chrome

### Versión del navegador

Navegador Versión 129.0.6668.58

### Sistema operativo en el cuál encuentras el problema

_windows 11_

### Pasos

| Paso | Descripción | Input Data |
|------|-------------|------------|
| 1    |   editar datos hacer click | trackmaster.systems
| 2    |     llenar campo nombre |  admite caracteres y numeros especiales
| 3    |     llenar campo apellido |  admite caracteres y numeros especiales
| 4    |     llenar campo correo   |  no cuenta con formato Valido

### Resultado esperado

Campos de formulario que tengan restricciones 

### Resultado actual

no cuenta con restricciones de caracteres especiales en campo , nombre, apellido y correo 

### Información adicional

evidencia de pruebas de aceptacion 
![Image](https://github.com/user-attachments/assets/78732506-c1d6-434f-84ba-0cdd50530e73)
// se confirma los datos modficados con los errores
![Image](https://github.com/user-attachments/assets/731f3c24-2ff2-429d-b933-8cf306ae8381)

**Comment by Catiel** [comment]
la severidad y la prioridad no siempre son alta y alta es depende si el bug hace que el sistema deje de funcionar asi que este reporte esta mal y tampoco es especifo solo me dices que no hay validaciones ni cuales son los tipos de validaciones @geovis159
