### ISSUE TITLE
El calendario de planificación permite ingresar fechas pasadas

### ISSUE THREAD

**Issue by PaoGalindo** [RedFox-SRL/backend#30]
### Severidad

Menor

### Prioridad

Baja

### Descripción

Al momento de escoger una fecha para algún evento nuevo, el sistema permite ingresar una fecha ya sea de inicio o fin que ya haya pasado.

### Pre-condiciones

Navegador Versión 128.0.6613.138
Ingresar como estudiante
Tener un grupo creado

### Tipo de dispositivo

Computadora

### ¿En qué navegadores encuentras el problema?

Chrome

### Versión del navegador

Navegador Versión 128.0.6613.138 (Build oficial) (64 bits)

### Sistema operativo en el cuál encuentras el problema

Windows

### Pasos

| Paso | Descripción | Input Data |
|------|-------------|------------|
| 1    |             |            |
| 2    |             |            |
| 3    |             |            |
| 4    |             |            |
| 5    |             |            |

### Resultado esperado

Rechazo al elegir una fecha pasada

### Resultado actual

El sistema acepta poner cualquier fecha

### Evidencias

![image](https://github.com/user-attachments/assets/4d49f6df-0d98-4ff4-82ef-64bd0b68960f)

**Comment by Catiel** [comment]
no se planeo esa restriccion ya que solo es un calendario donde se puede agregar eventos ya sean pasados o futuros
