### ISSUE TITLE
Se puede guardar un titulo con muchos espacios

### ISSUE THREAD

**Issue by PaoGalindo** [RedFox-SRL/backend#31]
### Severidad

Menor

### Prioridad

Baja

### Descripción

Al momento de crear un nuevo evento se puede guardar un nuevo evento con un titulo con puros espacios en blanco y una letra o numero al final

### Pre-condiciones

Navegador Versión 128.0.6613.138
Ingresar como estudiante
Tener un grupo creado

### Tipo de dispositivo

Computadora

### ¿En qué navegadores encuentras el problema?

Chrome

### Versión del navegador

Navegador Versión 128.0.6613.138 (Build oficial) (64 bits)

### Sistema operativo en el cuál encuentras el problema

Windows

### Pasos

| Paso | Descripción | Input Data |
|------|-------------|------------|
| 1    |             |            |
| 2    |             |            |
| 3    |             |            |
| 4    |             |            |
| 5    |             |            |

### Evidencias

![image](https://github.com/user-attachments/assets/99a62820-511c-4247-a274-3c655d2b1fb9)
![Captura de pantalla 2024-09-27 163854](https://github.com/user-attachments/assets/f9a3b44b-1a96-4ccb-bfc7-6601599736e9)

**Comment by Catiel** [comment]
al momento de recuperar el evento no se guardaron esos espacios al inicio
