### ISSUE TITLE
Los campos para crear un nuevo evento no son obligatorios

### ISSUE THREAD

**Issue by PaoGalindo** [RedFox-SRL/backend#33]
### Severidad

Menor

### Prioridad

Baja

### Descripción

Cuando se crea un nuevo evento, este se guarda de forma exitosa sin haber llenado todos los campos, como el de descripción.

### Pre-condiciones

Navegador Versión 128.0.6613.138
Ingresar como estudiante
Tener un grupo creado

### Tipo de dispositivo

Computadora

### ¿En qué navegadores encuentras el problema?

Chrome

### Versión del navegador

Navegador Versión 128.0.6613.138 (Build oficial) (64 bits)

### Sistema operativo en el cuál encuentras el problema

Windows

### Pasos

| Paso | Descripción | Input Data |
|------|-------------|------------|
| 1    |             |            |
| 2    |             |            |
| 3    |             |            |
| 4    |             |            |
| 5    |             |            |

### Resultado esperado

Mensaje que indique que todos los campos son obligatorios

### Resultado actual

Guardado exitoso sin llenar todos los campos

### Evidencias

![Captura de pantalla 2024-09-27 163854](https://github.com/user-attachments/assets/41dadfac-173a-4494-824f-4c019aa29ff1)

**Comment by Catiel** [comment]
El campo descripcion es opcional
