### ISSUE TITLE
El boton para guardar comentarios esta en singular

### ISSUE THREAD

**Issue by PaoGalindo** [RedFox-SRL/backend#75]
### Severidad

Cosmetica

### Prioridad

Baja

### Descripción

El boton que deberia decir "guardar evaluaciones" dice "guardar evaluacion", es diferente al mockup.

### Pre-condiciones

Navegador Versión 128.0.6613.138
Ingresar como docente

### Tipo de dispositivo

Computadora, Teléfono

### Modelo de teléfono si aplica

Samsung S20 FE

### ¿En qué navegadores encuentras el problema?

Chrome

### Versión del navegador

Navegador Versión 128.0.6613.138 (Build oficial) (64 bits)

### Sistema operativo en el cuál encuentras el problema

Windows, Android

### Pasos

| Paso | Descripción | Input Data |
|------|-------------|------------|
| 1    |             |            |
| 2    |             |            |
| 3    |             |            |
| 4    |             |            |
| 5    |             |            |

### Resultado esperado

boton "guardar evaluaciones"

### Resultado actual

boton "guardar evaluacion"

### Evidencias

![Captura de pantalla 2024-10-08 175416](https://github.com/user-attachments/assets/8f1cb1a6-6075-40c5-9a20-1c0d8650780a)

**Comment by Diego3520** [comment]
Se hizo el cambio a singular, debido a que se evalúa cada tarea uno a uno, por eso se dio el cambio para estar en singular
