### ISSUE TITLE
Se puede editar un correo con un formato que no es de correo

### ISSUE THREAD

**Issue by PaoGalindo** [RedFox-SRL/backend#78]
### Severidad

Mayor

### Prioridad

Alta

### Descripción

Al editar el correo de un curso y cambiarlo por otro el sistema acepta cualquier otro correo que no tenga formato de correos

### Pre-condiciones

Navegador Versión 128.0.6613.138 
Ingresar como estudiante
Editar datos

### Tipo de dispositivo

Computadora

### ¿En qué navegadores encuentras el problema?

Chrome

### Versión del navegador

Navegador Versión 128.0.6613.138 (Build oficial) (64 bits)

### Sistema operativo en el cuál encuentras el problema

Windows

### Pasos

| Paso | Descripción | Input Data |
|------|-------------|------------|
| 1    |             |            |
| 2    |             |            |
| 3    |             |            |
| 4    |             |            |
| 5    |             |            |

### Resultado esperado

Rechazo del sistema

### Resultado actual

Ingreso y cambio exitoso de este ingreso

### Evidencias

![Captura de pantalla 2024-10-09 195630](https://github.com/user-attachments/assets/189a0edc-f3d7-4135-81a5-bcfd2f1a2c1a)

**Comment by Catiel** [comment]
@PaoGalindo en realidad no es un bug ya que cumple el formato de un correo como existe varios dominios para un correo estos pueden ser desde @gmail.com hasta @redfox.com   o @redfox.sa
